### ISSUE TITLE
  IMS_PER_BATCH: 2 is Error

### ISSUE THREAD

**Issue by BachTuan1991** [ying09/TextFuseNet#22]
I run with batchsize = 1 is oke. but 2 have error.
`Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/media/data/bachtuan/TextFuseNet/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "tools/train_net.py", line 149, in main
    return trainer.train()
  File "/media/data/bachtuan/TextFuseNet/detectron2/engine/defaults.py", line 356, in train
    super().train(self.start_iter, self.max_iter)
  File "/media/data/bachtuan/TextFuseNet/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/media/data/bachtuan/TextFuseNet/detectron2/engine/train_loop.py", line 212, in run_step
    loss_dict = self.model(data)
  File "/home/asilla/miniconda3/envs/textfusenet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/data/bachtuan/TextFuseNet/detectron2/modeling/meta_arch/rcnn.py", line 88, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/asilla/miniconda3/envs/textfusenet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/data/bachtuan/TextFuseNet/detectron2/modeling/roi_heads/roi_heads.py", line 584, in forward
    losses.update(self._forward_mask(features_list, proposals, targets))
  File "/media/data/bachtuan/TextFuseNet/detectron2/modeling/roi_heads/roi_heads.py", line 684, in _forward_mask
    mask_features = self.mutil_path_fuse_module(mask_features, global_context, proposals)
  File "/home/asilla/miniconda3/envs/textfusenet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/data/bachtuan/TextFuseNet/detectron2/modeling/roi_heads/mutil_path_fuse_module.py", line 94, in forward
    text = x[char_pos[i]]
IndexError: The shape of the mask [2] at index 0does not match the shape of the indexed tensor [9, 256, 14, 14] at index 0
`

**Comment by BachTuan1991** [comment]
oh. i think it's config of GPU because i run `python tools/train_net.py --num-gpus 2 --config-file configs/ocr/icdar2013_101_FPN.yaml` is not error
