### ISSUE TITLE
ImportError: cannot import name '_C' from 'detectron2' 

### ISSUE THREAD

**Issue by TianhaoFu** [ying09/TextFuseNet#45]
Hi, I'm trying to run your demo.  

I installed the pytorch environment follow your 'step-by-step installation.txt'. 
But when I use `python demo/icdar2015_detection.py` to run the demo. I came across this problem . 
```

Traceback (most recent call last):
  File "demo/icdar2015_detection.py", line 12, in <module>
    from detectron2.data.detection_utils import read_image
  File "C:\Users\Tianh\Desktop\1-detect\TextFuseNet-master\demo\detectron2\data\__init__.py", line 4, in <module>
    from .build import (
  File "C:\Users\Tianh\Desktop\1-detect\TextFuseNet-master\demo\detectron2\data\build.py", line 13, in <module>
    from detectron2.structures import BoxMode
  File "C:\Users\Tianh\Desktop\1-detect\TextFuseNet-master\demo\detectron2\structures\__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_iou
  File "C:\Users\Tianh\Desktop\1-detect\TextFuseNet-master\demo\detectron2\structures\boxes.py", line 7, in <module>
    from detectron2.layers import cat
  File "C:\Users\Tianh\Desktop\1-detect\TextFuseNet-master\demo\detectron2\layers\__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "C:\Users\Tianh\Desktop\1-detect\TextFuseNet-master\demo\detectron2\layers\deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: cannot import name '_C' from 'detectron2' (C:\Users\Tianh\Desktop\calibration\1-detect\TextFuseNet-master\demo\detectron2\__init__.py)
```

Do you know why? Thanks!

**Comment by watanka** [comment]
try run 
`python setup.py build develop` and do it again
It solved the issue In my case

**Comment by ChangWinnie** [comment]
@TianhaoFu I have the same problem, have you solved it?

I  run python setup.py build develop  successfully, but it still shows the error.

**Comment by 123cjjjj** [comment]
> 

I have the same problem, have you solved it?

**Comment by Xiuxiu21** [comment]
> python setup.py build develop请问您解决了吗
