### ISSUE TITLE
RuntimeError:CUDA out of memory

### ISSUE THREAD

**Issue by watanka** [ying09/TextFuseNet#46]
I'm aware that this is more hardware issue of mine, but I was wondering if there is any way I can make the model little bit smaller to save GPU memory. Thank you in advance!

**Comment by Real-YeJ** [comment]
@watanka  use smaller image sizes

**Comment by bhrt-sharma** [comment]
is there any other solution, to this problem?

**Comment by 25b3nk** [comment]
As suggested by @Real-YeJ , after reducing the `MIN_SIZE_TEST` parameter and `MAX_SIZE_TEST` parameter in `./configs/ocr/icdar2015_101_FPN.yaml`, I could get the demo running on my system. One can change the corresponding `config` file for the demo they want to run.

**Comment by S130111** [comment]
I modified MIN_SIZE_TEST and MAX_SIZE_TEST and the following errors occurred. Can you tell me if you modified those parameters?
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/home/root1/SHI/TextFuseNet/detectron2/engine/launch.py", line 52, in launch
    main_func(*args)
  File "tools/train_net.py", line 149, in main
    return trainer.train()
  File "/home/root1/SHI/TextFuseNet/detectron2/engine/defaults.py", line 356, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/root1/SHI/TextFuseNet/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/home/root1/SHI/TextFuseNet/detectron2/engine/train_loop.py", line 212, in run_step
    loss_dict = self.model(data)
  File "/home/software/anaconda2019/envs/textfusenet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/root1/SHI/TextFuseNet/detectron2/modeling/meta_arch/rcnn.py", line 88, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/software/anaconda2019/envs/textfusenet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/root1/SHI/TextFuseNet/detectron2/modeling/roi_heads/roi_heads.py", line 584, in forward
    losses.update(self._forward_mask(features_list, proposals, targets))
  File "/home/root1/SHI/TextFuseNet/detectron2/modeling/roi_heads/roi_heads.py", line 684, in _forward_mask
    mask_features = self.mutil_path_fuse_module(mask_features, global_context, proposals)
  File "/home/software/anaconda2019/envs/textfusenet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/root1/SHI/TextFuseNet/detectron2/modeling/roi_heads/mutil_path_fuse_module.py", line 94, in forward
    text = x[char_pos[i]]
IndexError: The shape of the mask [51] at index 0does not match the shape of the indexed tensor [162, 256, 14, 14] at index 0
@ @25b3nk @Real-YeJ
