### ISSUE TITLE
demo error. _C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: 

### ISSUE THREAD

**Issue by jireh-father** [ying09/TextFuseNet#5]
I followed the step-by-step installation. (https://github.com/ying09/TextFuseNet/blob/master/step-by-step%20installation.txt)
I got an error for running the demo.

Traceback (most recent call last):
  File "demo/icdar2013_detection.py", line 12, in <module>
    from detectron2.data.detection_utils import read_image
  File "/home/ubuntu/source/TextFuseNet/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/ubuntu/source/TextFuseNet/detectron2/data/build.py", line 13, in <module>
    from detectron2.structures import BoxMode
  File "/home/ubuntu/source/TextFuseNet/detectron2/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_iou
  File "/home/ubuntu/source/TextFuseNet/detectron2/structures/boxes.py", line 7, in <module>
    from detectron2.layers import cat
  File "/home/ubuntu/source/TextFuseNet/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/ubuntu/source/TextFuseNet/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: /home/ubuntu/source/TextFuseNet/detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by jireh-father** [comment]
I resolved this issue.

**Comment by xxAna** [comment]
@jireh-father how do you solve it? Could you share your solution with me? Thank you very much!

**Comment by Hardik1608** [comment]
@jireh-father, can you please tell how did you solve it?
